"""Adicionando chaves estrangeiras em Requisito

Revision ID: 5fbaa0f46a37
Revises: fa5c39c8361e
Create Date: 2025-02-11 23:12:19.113040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fbaa0f46a37'
down_revision: Union[str, None] = 'fa5c39c8361e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projetos_user_id_fkey', 'projetos', type_='foreignkey')
    op.drop_column('projetos', 'descricao')
    op.drop_column('projetos', 'user_id')
    op.add_column('requisitos', sa.Column('projeto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requisitos', 'projetos', ['projeto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requisitos', type_='foreignkey')
    op.drop_column('requisitos', 'projeto_id')
    op.add_column('projetos', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projetos', sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('projetos_user_id_fkey', 'projetos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
