"""Criando tabelas iniciais

Revision ID: 65ccf0f4402d
Revises: 
Create Date: 2025-02-11 22:11:22.489520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65ccf0f4402d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.add_column('requisitos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('requisitos', 'descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.create_index(op.f('ix_requisitos_titulo'), 'requisitos', ['titulo'], unique=False)
    op.drop_constraint('requisitos_projeto_id_fkey', 'requisitos', type_='foreignkey')
    op.create_foreign_key(None, 'requisitos', 'users', ['user_id'], ['id'])
    op.drop_column('requisitos', 'versao')
    op.drop_column('requisitos', 'data_criacao')
    op.drop_column('requisitos', 'status')
    op.drop_column('requisitos', 'projeto_id')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.add_column('requisitos', sa.Column('projeto_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('requisitos', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('requisitos', sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('requisitos', sa.Column('versao', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requisitos', type_='foreignkey')
    op.create_foreign_key('requisitos_projeto_id_fkey', 'requisitos', 'projetos', ['projeto_id'], ['id'])
    op.drop_index(op.f('ix_requisitos_titulo'), table_name='requisitos')
    op.alter_column('requisitos', 'descricao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('requisitos', 'user_id')
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data_criacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey'),
    sa.UniqueConstraint('email', name='usuarios_email_key')
    )
    # ### end Alembic commands ###
