"""Adicionando campo status em requisitos

Revision ID: 65f9417938e4
Revises: 71bcc3526e95
Create Date: 2025-02-11 22:59:49.895950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f9417938e4'
down_revision: Union[str, None] = '71bcc3526e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisitos', sa.Column('status', sa.String(), nullable=True))
    op.add_column('requisitos', sa.Column('versao', sa.String(), nullable=True))
    op.add_column('requisitos', sa.Column('data_criacao', sa.DateTime(), nullable=True))
    op.add_column('requisitos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('requisitos', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_requisitos_titulo', table_name='requisitos')
    op.drop_constraint('requisitos_projeto_id_fkey', 'requisitos', type_='foreignkey')
    op.create_foreign_key(None, 'requisitos', 'users', ['user_id'], ['id'])
    op.drop_column('requisitos', 'projeto_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisitos', sa.Column('projeto_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requisitos', type_='foreignkey')
    op.create_foreign_key('requisitos_projeto_id_fkey', 'requisitos', 'projetos', ['projeto_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_requisitos_titulo', 'requisitos', ['titulo'], unique=False)
    op.alter_column('requisitos', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('requisitos', 'user_id')
    op.drop_column('requisitos', 'data_criacao')
    op.drop_column('requisitos', 'versao')
    op.drop_column('requisitos', 'status')
    # ### end Alembic commands ###
