"""Corrigindo relacionamento entre Projetos e Requisitos

Revision ID: 71bcc3526e95
Revises: f3c0a6e03b2f
Create Date: 2025-02-11 22:19:07.191690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bcc3526e95'
down_revision: Union[str, None] = 'f3c0a6e03b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('projetos', 'descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.create_foreign_key(None, 'projetos', 'users', ['user_id'], ['id'])
    op.add_column('requisitos', sa.Column('projeto_id', sa.Integer(), nullable=True))
    op.drop_constraint('requisitos_user_id_fkey', 'requisitos', type_='foreignkey')
    op.create_foreign_key(None, 'requisitos', 'projetos', ['projeto_id'], ['id'], ondelete='CASCADE')
    op.drop_column('requisitos', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisitos', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requisitos', type_='foreignkey')
    op.create_foreign_key('requisitos_user_id_fkey', 'requisitos', 'users', ['user_id'], ['id'])
    op.drop_column('requisitos', 'projeto_id')
    op.drop_constraint(None, 'projetos', type_='foreignkey')
    op.alter_column('projetos', 'descricao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('projetos', 'user_id')
    # ### end Alembic commands ###
