"""Adicionando campo status em requisitos

Revision ID: fa5c39c8361e
Revises: 65f9417938e4
Create Date: 2025-02-11 23:05:36.013320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5c39c8361e'
down_revision: Union[str, None] = '65f9417938e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
